config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  
  #action cable
  mount ActionCable.server => '/cable'

  resources :products do
    member do
      delete '/destroy', to: 'products#destroy', as: :destroy
    end

    resources :comments, only: [:create, :destroy]
  end

  resources :activity_logs, only: [:index] do
    collection do
      get 'search'
    end
  end

  resources :carts do
    member do
      # actions new, add product, remove product
      get '/new_cart', to: 'carts#new', as: :new_cart # Cart
      match '/add_to_cart/product_id', action: :add_to_cart, via: [:get, :post], as: :add_to_cart # CartItem, Cart, and Product
      match '/remove_product_from_cart/:product_id', action: :remove_product_from_cart, via: [:get, :delete], as: :remove_product_from_cart
      
      # update quantity, and downgrade quantity(if > 1)
      match '/update_quantity/:product_id', action: :update_quantity, via: [:get, :patch], as: :update_quantity
      match '/downgrade_quantity/:product_id', action: :downgrade_quantity, via: [:get, :patch], as: :downgrade_quantity
      
      # checkout and make empty again cart of user BEFORE completed the order.
      get '/checkout', to: 'carts#checkout', as: :checkout # CartItem
      match 'destroy_all_items', via: [:get, :post]
    end
  end

  get '/index', to: 'pages#index', as: :index
  get '/history', to: 'pages#history', as: :history
  # Defines the root path route ("/")
  root "pages#home"
end

app/views/pages/home.html.erb
<div class="cor-portfolio">
  <nav class="nav-portfolio">
    <div class="nav-portfolio-logo">
      <a href="#">
        <img src="">
      </a>
    </div>
  
    <ul class="nav-portfolio-links">
      <li class="link-portfolio"><a href="<%= index_path %>">Ecommerce</a></li>
      <li class="link-portfolio"><a href="#projects">Projects</a></li>
    </ul>
  </nav>
  <br>
  <div class="header container-portfolio">
    <div class="content-portfolio">
      <h4>Are you looking for a Ruby On Rails developer?</h4>
      <h1>Hi, im <span>Washington</span>, ROR Developer</h1>
      <p>
      I'm a Ruby on Rails 7 programmer
      </p>
      <br>
      <button class="btn-portfolio" id="scrollButton">Get Started</button>
    </div>
    <div class="image-portfolio">
      <img src="https://i.imgur.com/MPcxF5A.png">
    </div>
    <div class="section-portfolio" id="projects">
    <h2 class="header">My Projects</h2>
      <div class="learn">
        <div class="card-portfolio">
          <span><box-icon name='github' type='logo' ></box-icon> </span>
          <h4>My GitHub</h4>
          <p>
            You can access my github to learn about my projects, including this one, made in Ruby on Rails 7.1.
          </p>
          <a href="https://github.com/wasdevv">Acess my GitHub</a>
        </div>
        <div class="card-portfolio">
          <span><box-icon name='linkedin' type='logo' ></box-icon> </span>
          <h4>My Linkedin</h4>
          <p>
            You can access my github to learn about my projects, including this one, made in Ruby on Rails 7.1.
          </p>
          <a href="https://www.linkedin.com/in/washington-cardoso-6a3558261/">Acess my Linkedin</a>
        </div>
        <div class="card-portfolio">
          <span><box-icon name='store'></box-icon> </span>
          <h4>My E-commerce</h4>
          <p>
            You can access my ecommerce repository, this project is a Ruby on Rails 7.1 Modern e-commerce.
          </p>
          <a href="https://github.com/wasdevv/ecommerce_rails">Acess my E-commerce</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<section class="home">
  <div class="home-text">
    <h4>Simple Ecommerce in Rails 7</h4>
    <h1>Boost your sales with Ruby Shop!</h1>
    <a href="#product" class="btn-index">Explore Now</a>
  </div>

  <div class="home-image.img">
    <img src="https://i.imgur.com/LcXzAu7.png">
  </div>
</section>
<%# section feature %>
<section class="feature">
  <div class="middle-text-index">
    <h2>More features, have examples above, discover.</h2>
    <h3>Info-products, clothes, and everything else at <strong>Ruby Shop</strong></h3>
  </div>
  <br>
  <div class="feature-content">
    <div class="row">
      <div class="main-row">
        <div class="row-text">
          <h6>Explore the Products</h6>
          <a href="#" class="row-btn">Show me all</a>
          <div class="row-img">
            <img src="https://i.imgur.com/J6a1zwh.png">
            <img src="https://i.imgur.com/qOMFZ0B.png">
            <img src="https://i.imgur.com/nIKKbna.png">
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="product" class="product">
  <div class="middle-text-index">
    <h2>Available<strong> products</strong></h2>
  </div>

<% @products.each do |product| %>
  <div>
    <div class="product-content">
      <div class="box">
        <div class="box-img">
          <% if product.image.attached? %>
            <%= image_tag(product.image.variant(resize: "100x100")) %>
          <% else %>
            <%= image_tag("https://i.imgur.com/jl1rTQL.png", width: 100, height: 100) %>
          <% end %>
        </div>
        <h3>Owner: <%= product.user.email %></h3>
        <h3><%= product.name %></h3>
        <h4><%= product.description %></h4>
        <div class="inbox">
          <div>
            <a href="#" class="price"><%= number_to_currency(product.price, unit: 'R$', separator: ',', delimiter: '.') %></a>
            <% if product && current_user == product.user %>
              <%= link_to "Edit", edit_product_path(product), class: "edit" %>
            <% end %>
          </div>
          <div class="rating">
            <% (1..5).each do |i| %>
              <a href="#"><i class="bi bi-star-fill"></i></a>
            <% end %>
          </div>
        </div>
        <div class="heart">
          <i class="bi bi-suit-heart"></i>
        </div>
      </div>
    </div>
  </div>
<% end %>
</section>

<%# contact %>
<section class="contact">
  <div class="main-contact">
    <div class="contact-content">
      <h5>Getting started</h5>
      <li><a href="#">Release Notes</a></li>
      <li><a href="#">Dark Mode</a></li>
      <li><a href="#">Browser Support</a></li>
      <li><a href="#">Upgrade Guide</a></li>
    </div>

    <div class="contact-content">
      <h5>Explore</h5>
      <li><a href="#">Prototyping</a></li>
      <li><a href="#">Design systems</a></li>
      <li><a href="#">Pricing</a></li>
      <li><a href="#">Security SSL</a></li>
    </div>

    <div class="contact-content">
      <h5>Resources</h5>
      <li><a href="#">Best practices</a></li>
      <li><a href="#">Support</a></li>
      <li><a href="#">Developers</a></li>
      <li><a href="#">Learn Design</a></li>
    </div>

    <div class="contact-content">
      <h5>Community</h5>
      <li><a href="#">Discussion Forums</a></li>
      <li><a href="#">Code of Conduct</a></li>
      <li><a href="#">Contributing</a></li>
      <li><a href="#">API Reference</a></li>
    </div>
  </div>
</section>

<div class="end-text">
  <p>© 2024 All Rights Reserved by Washington Pereira</p>
</div>