config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  
  #action cable
  mount ActionCable.server => '/cable'

  resources :products do
    member do
      delete '/destroy', to: 'products#destroy', as: :destroy
    end

    resources :comments, only: [:create, :destroy]
  end

  resources :activity_logs, only: [:index] do
    collection do
      get 'search'
    end
  end

  resources :carts do
    member do
      # actions new, add product, remove product
      get '/new_cart', to: 'carts#new', as: :new_cart # Cart
      match '/add_to_cart/product_id', action: :add_to_cart, via: [:get, :post], as: :add_to_cart # CartItem, Cart, and Product
      match '/remove_product_from_cart/:product_id', action: :remove_product_from_cart, via: [:get, :delete], as: :remove_product_from_cart
      
      # update quantity, and downgrade quantity(if > 1)
      match '/update_quantity/:product_id', action: :update_quantity, via: [:get, :patch], as: :update_quantity
      match '/downgrade_quantity/:product_id', action: :downgrade_quantity, via: [:get, :patch], as: :downgrade_quantity
      
      # checkout and make empty again cart of user BEFORE completed the order.
      get '/checkout', to: 'carts#checkout', as: :checkout # CartItem
      match 'destroy_all_items', via: [:get, :post]
    end
  end

  get '/index', to: 'pages#index', as: :index
  get '/history', to: 'pages#history', as: :history
  # Defines the root path route ("/")
  root "pages#home"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user

  has_many :cart_items, class_name: 'CartItem', dependent: :destroy
  has_many :products, through: :cart_items, dependent: :destroy
  has_many :order_tiems, through: :order
  
  has_many :activity_logs, as: :trackable, dependent: :destroy
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :authenticate_user!, only: [:add_to_cart]

    # without payment logistic, ONLY BACK-END
    def new
        # if the user have one cart
        if current_user.cart.present?
            redirect_to cart_path(current_user.cart)
        else
            # make a new cart
            @cart = current_user.build_cart

            # if make correcly the cart
            if @cart.save
                create_activity_log(:created_Cart, @cart, details: { message: 'Created a cart' })
                redirect_to cart_path(current_user.cart)
            end
        end
    end

    def add_to_cart

        @product = Product.find_by(id: params[:product_id])
        if current_user.id == @product.user_id
            flash[:error] = "You can not buy your own product"
            redirect_to root_path
            return
        end

        if @product
            @cart = current_user.cart || current_user.build_cart
            cart_item = @cart.cart_items.find_or_initialize_by( product: @product )
            cart_item.quantity ||= 1
            cart_item.assign_attributes(price: @product.price)
            cart_item.save!

            ActionCable.server.broadcast("cart_channel_#{current_user.id}", { action: 'update_cart', cart: @cart })
            create_activity_log(:added_to_cart, cart_item, details: { message: 'Product added to cart' })
        end

        redirect_to cart_path, notice: 'Product added to your cart.'
        return
    end

    def update_quantity
        @cart = current_user.cart
        @product = Product.find_by(id: params[:product_id])
        @cart_item = @cart.cart_items.find_or_initialize_by(product: @product)
        new_quantity = @cart_item.quantity + 1

        ActionCable.server.broadcast("cart_channel_#{current_user.id}", { action: 'update_cart', cart: @cart })
        if @cart_item.update(quantity: new_quantity)
            redirect_to cart_path(@cart)#, notice: 'Quantidade do carrinho atualizada com sucesso.'
        else
            redirect_to cart_path(@cart)#, alert: 'Erro ao atualizar a quantidade do carrinho.'
        end
    end

    def downgrade_quantity
        @cart = current_user.cart
        @product = Product.find_by(id: params[:product_id])
        @cart_item = @cart.cart_items.find_or_initialize_by(product: @product)

        if @cart_item && @cart_item.quantity > 1
            new_quantity = @cart_item.quantity - 1
            puts "Old Quantity: #{@cart_item.quantity}, New Quantity: #{new_quantity}"
            
            if @cart_item && @cart_item.quantity > 1
                new_quantity = @cart_item.quantity - 1
            
                if @cart_item.update(quantity: new_quantity)
                    redirect_to cart_path(@cart)#, notice: 'Cart quantity updated successfully.'
                else
                    redirect_to cart_path(@cart)#, alert: 'Error updating cart quantity.'
                end
            elsif @cart_item && @cart_item.quantity == 1
                if @cart_item.destroy
                    redirect_to cart_path(@cart)#, notice: 'Cart quantity updated successfully.'
                else
                    redirect_to cart_path(@cart)#, alert: 'Error updating cart quantity.'
                end
            else
                puts "Cart item not found or quantity not set."
                redirect_to cart_path(@cart)#, alert: 'Error updating cart quantity.'
            end
        end
    end

    # render the _cart_table.html.erb
    def show
        @cart = current_user.cart || current_user.build_cart
        @product = Product.find_by(id: params[:product_id])
        @cart_items = @cart.cart_items

        if @cart.cart_items.empty?
            redirect_to root_path
        end
    end

    def remove_product_from_cart
        @cart = current_user.cart
        @product = Product.find_by(id: params[:product_id])
        @cart_item = @cart.cart_items.find_by(product: @product)

        if @cart_item
            @cart_item.destroy
            create_activity_log(:removed_from_cart, @cart_item, details: { message: 'Product has been removed from cart'})
            
            # action cable
            ActionCable.server.broadcast("cart_channel_#{current_user.id}", { action: 'product_removed', product_id: @product.id })
            Rails.logger.info("Broadcasted product_removed to CartChannel")
            
            if @cart.cart_items.empty?
                redirect_to products_path
            else
                redirect_to cart_path(current_user.cart), notice: 'Your product has benn removed from your cart'
            end
        else
            redirect_to @cart, notice: 'Not possible to remove your product, try again.'
        end
    end

    def destroy
        current_user.destroy
        create_activity_log(:deleted_cart, @cart, details: { message: 'Deleted a cart'})

        @order = current_user.orders.build

        @cart_items.each do |cart_item|
            @order.order_items.build(
                product: cart_item.product,
                quantity: cart_item.quantity,
                price: cart_item.price
            )
        end

        if @order.save
            create_activity_log(:created_order, @order, details: { message: 'Created a order'})
        end
    end

    def checkout
        @cart = current_user.cart
        @cart_items = @cart.cart_items

        @order = current_user.orders.build

        @cart_items.each do |cart_item|
            @order.order_items.build(
                product: cart_item.product,
                quantity: cart_item.quantity,
                price: cart_item.price
            )
        end

        if @order.save
            create_activity_log(:created_order, @order, details: { message: 'Order created '})
        end
    end

    def destroy_all_items
        @order = current_user.orders.build
        @order.save

        create_activity_log(:created_history, @order, details: { message: 'Order archived in user history'})

        current_user.cart.cart_items.each do |cart_item|
            @order.order_items.create(product: cart_item.product, quantity: cart_item.quantity, price: cart_item.price )
        end

        create_activity_log(:removed_all_items, current_user.cart, details: { message: 'Removing items from cart' })
        current_user.cart.cart_items.destroy_all
        redirect_to root_path, notice: 'Thank you for choosing our store'
    end

    private

    def create_activity_log(action, trackable, details: {})
        ActivityLog.create!(user: current_user, action: action, trackable: trackable, details: details)
    end
end

app/views/carts/_cart_table.html.erb
<br>
<br>
<br>
<table class="table table-borderless w-auto ms-4">
  <caption>Want to buy more? <%= link_to "Buy More", products_path %></caption>
  <% total_order = 0 %>

  <% @cart_items.each do |cart_item| %>
    <% total_order += cart_item.quantity * cart_item.price %>
  <% end %>

  <caption>Total Order: <%= number_to_currency(total_order)%></caption>
    <thead class="table-light">
      <tr>
        <th scope="col" class="text-center">Product</th>
        <th scope="col" class="text-center">Quantity</th>
        <th scope="col" class="text-center">Unit Price</th>
      <%# <th scope="col" class="text-center">ID da compra EM BREVE</th> %>
      </tr>
    </thead>
    <tbody>
      <% @cart_items.each do |cart_item| %>
        <tr>
          <td class="align-middle text-center"><%= cart_item.product.name %></td>
          <td class="align-middle text-center">
            <%= link_to "‹", downgrade_quantity_cart_path(@cart, product_id: cart_item.product.id), method: :patch, class: "text-custom-add1" %> 
            <%= cart_item.quantity %>
            <%= link_to "›", update_quantity_cart_path(@cart, product_id: cart_item.product.id), method: :patch, class: "text-custom-add", id: "update-link" %> 
          </td>
          <td class="align-middle text-center"><%= number_to_currency(cart_item.price) %></td>
          <td class="align-middle text-center">
            <%= link_to "Remove", remove_product_from_cart_cart_path(product_id: cart_item.product.id ), class: "remove-button-custom"%>
          </td>
        </tr>
      <% end %>
    </tbody>
</table>
<br>
<div class="card custom-margin-left" style="width: 35rem;">
  <div class="card-body">
    <h5 class="card-title"><strong>Information and Guarantees</strong></h5>
    <h6 class="card-subtitle mb-2 text-body-secondary">Ruby Shop</h6>
    <p class="card-text">Delivery made by: <strong>Ruby Shop</strong>!</p>
    <a href="https://localhost:3000" class="card-link">Increase Warranty</a>
    <a href="https://localhost:3000" class="card-link">Anti-Theft Guarantee</a>
    <%= link_to "Confirm Order", checkout_cart_path(current_user), class: "card-link"%>
  </div>
</div>

app/views/carts/checkout.html.erb
<br>
<br>
<br>
<br>
<br>
<div class="text-center" >
  <p>Pedido</p>
</div>

<table class="table table-light table-bordered w-auto ms-4">
  <thead class="table-light">
    <tr>
      <th scope="col" class="text-center">Pedido</th>
  <tbody>
    <% @cart_items.each do |cart_item| %>
      <tr>
        <td class="align-middle text-center"><%= cart_item.product.name %></td>
        <td class="align-middle text-center"><%= cart_item.quantity %></td>
        <td class="align-middle text-center"><%= number_to_currency(cart_item.price) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Voltar à tela inicial", destroy_all_items_cart_path(current_user), method: :delete %>

app/views/carts/show.html.erb
<turbo-frame id="cart">
  <%= render "cart_table", locals: { @cart_items => @cart.cart_items } %>
</turbo-frame>