config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check
  
  #action cable
  mount ActionCable.server => '/cable'

  resources :products do
    member do
      delete '/destroy', to: 'products#destroy', as: :destroy
    end

    resources :comments, only: [:create, :destroy]
  end

  resources :activity_logs, only: [:index] do
    collection do
      get 'search'
    end
  end

  resources :carts do
    member do
      # actions new, add product, remove product
      get '/new_cart', to: 'carts#new', as: :new_cart # Cart
      match '/add_to_cart/product_id', action: :add_to_cart, via: [:get, :post], as: :add_to_cart # CartItem, Cart, and Product
      match '/remove_product_from_cart/:product_id', action: :remove_product_from_cart, via: [:get, :delete], as: :remove_product_from_cart
      
      # update quantity, and downgrade quantity(if > 1)
      match '/update_quantity/:product_id', action: :update_quantity, via: [:get, :patch], as: :update_quantity
      match '/downgrade_quantity/:product_id', action: :downgrade_quantity, via: [:get, :patch], as: :downgrade_quantity
      
      # checkout and make empty again cart of user BEFORE completed the order.
      get '/checkout', to: 'carts#checkout', as: :checkout # CartItem
      match 'destroy_all_items', via: [:get, :post]
    end
  end

  get '/index', to: 'pages#index', as: :index
  get '/history', to: 'pages#history', as: :history
  # Defines the root path route ("/")
  root "pages#home"
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user

    has_many :cart_items
    has_many :carts, through: :cart_items
    has_many :comments

    validates :name, presence: true
    validates :quantity, numericality: { only_integer: true}
    validates :price, numericality: { greater_than_or_equal_to: 0 }
    validates :description, presence: true

    has_many :activity_logs, as: :trackable, dependent: :destroy

    # active storage image
    has_one_attached :image
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
    end

    def new
        @product = Product.new
    end

    def create
        @product = current_user.products.build(product_params)
        if @product.save
            create_activity_log(:product_created, @product, details: { message: 'Product created'})
            flash[:success] = "Product created!"
            redirect_to index_pages_path
        else
            render :new
        end
    end

    def show
        @product = Product.find(params[:id])
    end

    def edit
        @product = Product.find(params[:id])
    end

    def update
        @product = Product.find(params[:id])
        if @product.update(product_params)
            create_activity_log(:product_updated, @product, details: { message: 'Product updated' })
            redirect_to product_path(@product)
            flash[:success] = "Product updated!"
        else
            render :edit
        end
    end

    def destroy
        @product = Product.find(params[:id])
        @product.destroy
        create_activity_log(:product_deleted, @product, details: { message: 'Product removed '})
        flash[:danger] = "Product deleted."
        redirect_to index_pages_path
    end
    
    private

    def product_params
        params.require(:product).permit(:name, :quantity, :price, :description, :image)
    end

    def create_activity_log(action, trackable, details: {} )
        ActivityLog.create!(user: current_user, action: action, trackable: trackable, details: details)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<br>
<br>
<br>
<h1>Product#edit</h1>
<p>Find me in app/views/product/edit.html.erb</p>

app/views/products/index.html.erb
<br>
<br>
<br>
<div class="text-center">
  <h2>Ecommerce feito em <strong>Ruby on Rails 7.1</strong></h2>
</div>
<br>
<div class="card custom-margin-left" style="width: 28rem;">
  <div class="card-body">
    <h5 class="card-title">Shop Ruby, o ecommerce em Rails 7.1!</h5>
    <h6 class="card-subtitle mb-2 text-body-secondary">Ecommerce Shop Ruby</h6>
    <p class="card-text">Conheça Shop Ruby, Meu maior projeto de ecommerce de portfólio!</p>
    <a href="https://github.com/wasdevv/ecommerce_rails" class="card-link">Repositório</a>
    <a href="https://www.linkedin.com/in/washington-cardoso-6a3558261/" class="card-link">Linkedin</a>
  </div>
</div>

<div class="product-container">
 <% @products.each do |product| %>
    <div class="product product-left" id="product-<%= product.id %>" onclick="window.location.href='<%= product_path(product) %>';">
      <p class="product-name fs-5"><strong><%= product.name %> </strong></p>
      <p class="product-info"><strong>Price: <%= number_to_currency(product.price, unit: 'R$', separator: ',', delimiter: '.') %> </strong></p>
      <p class="product-description"><strong>Description: <%= product.description %> </strong></p>
    </div>
 <% end %>
</div>
<div class="politics">
  ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀Politicas de Privacidades
</div>

app/views/products/new.html.erb
<br>
<br>
<br>
<div class="text-center">
<p>New <strong>Product</strong></p>
</div>

<%= form_for @product do |f| %>

<%= f.label :Name %>
<%= f.text_field :name, placeholder: "Type a name" %>
<br>
<%= f.label :Quantity %>
<%= f.number_field :quantity, placeholder: "Type a Quantity" %>
<br>
<%= f.label :Price %>
<%= f.number_field :price, placeholder: "Type a Price" %>
<br>
<%= f.label :Description %>
<%= f.text_field :description, placeholder: "Type a Description" %>
<br>
<%= f.label :Image %>
<%= f.file_field :image %>
<br>
<%= f.submit 'Create Product' %>
<% end %>

app/views/products/show.html.erb
<br>
<br>
<br>
<div class="container details-container">
  <div class="details-header">
    <p>Details of <strong>Product </strong>ID: <%= @product.id %> </p>
  </div>
</div>

<div class="container-show">
  <div class="product-description-show">
    <p class="text-black"><strong><i class="bi bi-file-earmark-text"></i> Description of Product:</strong></p>
    <br>
    <br>
    <p class="text-black"><%= @product.description %></p>
    <div class="info-product-container">
      <p class="text-start fs-6 text-black">Product by: <strong><%= @product.user.email %></strong></p>
      <p class="text-start fs-2 text-dark"><strong><%= number_to_currency(@product.price, unit: 'R$', separator: ',', delimiter: '.') %></p>
      <p class="text-start fs-5 text-dark">Adittions <strong>Coming Soon!</strong></p>
      <br>
      <%= button_to(add_to_cart_cart_path(product_id: @product.id), method: :post, class: "btn btn-primary") do %>
        Add into Cart <i class="bi bi-plus-circle"></i>
      <% end %>
    </div>
  </div>
</div>